"""add_deep_search_credits_to_user

Revision ID: 47836e494dde
Revises: 30cab2a16c9f
Create Date: 2026-09-08 18:51:57.068001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47836e494dde'
down_revision: Union[str, Sequence[str], None] = '30cab2a16c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deep_search_credits', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deep_search_credits')
    # ### end Alembic commands ###
